name: Build, Push e Deploy (Azure App Service)

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}/finance-proativa
  WEBAPP_NAME: app-fin-proa-final

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 1. Checkout do Codigo
      uses: actions/checkout@v4
      
    - name: 2. Login no Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: 3. Definir Tag da Imagem
      id: set_tag
      run: echo "IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
    
    - name: 4. Construir e Marcar a Imagem
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_REPO }}:${{ env.IMAGE_TAG }}

    - name: 5. Deploy no Azure App Service
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.WEBAPP_NAME }}
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} 
        images: ${{ env.DOCKER_REPO }}:${{ env.IMAGE_TAG }}